### ISSUE TITLE
Add CSS Reset to the project.

### ISSUE THREAD

**Issue by CGuiho** [juniorfuta/currency-converter#40]
# Add CSS Reset 

## 1. Create: `styles/reset.css`

With the content:

```css

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Roboto', sans-serif;
}

```

## 2. Add it to the HTML

Add to the HTML head
```html
<link rel="stylesheet" href="styles/reset.css" />
```
