### ISSUE TITLE
Setup body tage.

### ISSUE THREAD

**Issue by CGuiho** [juniorfuta/currency-converter#41]
# Add `page-setup.css`

## 1. Create: `styles/page-setup.css`

With the content:

```css
body {
  min-height: 100vh;

  display: flex;
  flex-direction: column;  
  justify-content: space-between;
}
```

## 2. Add it to the HTML

<strong>Add to the HTML head</strong>
```html
<link rel="stylesheet" href="styles/page-setup.css" />
```
