### ISSUE TITLE
My final `styles1.css`

### ISSUE THREAD

**Issue by CGuiho** [juniorfuta/currency-converter#43]
My final  `styles1.css`:

```css

/*
By: PalancaTechnologies Softwares 
CEO: Júnior Futa
a.k.a: JFuta21
Email: juniorfuta94@gmail.com
Instagram: @juniorfuta
*/

* {
    box-sizing: border-box;
    font-family: Arial, Helvetica, sans-serif;
}

.container h2 {
    /* font-size: 90%; */
    font-size: 20px;
}

#navbar {
    display: flex;
    justify-content: space-between;
    /* width: 100%; */
    border: solid 1px #111;
    border-radius: 10px;
    color: rgb(41, 130, 189);
    flex-direction: row;
}

#logo {
    display: flex;
    gap: 4px;
    flex-direction: row;
    justify-content: center;
    /* background-color: chocolate; */
    margin-left: 130px;
}

#logo img {
    margin-top: 15px;
    width: 27px;
    height: 27px;
}

#canadian-flag {
    border-radius: 15px;
}

#container {
    display: inline-block;
    cursor: pointer;
    margin: 10px 20px;
    /* background-color: crimson; */
}

.bar1,
.bar2,
.bar3 {
    width: 30px;
    height: 5px;
    background-color:#3498DB;
    margin: 6px 0px;
    transition: 0.4s;
}

.change .bar1 {
    transform: translate(0, 11px) rotate(-45deg);
}

.change .bar2 {
    opacity: 0;
}

.change .bar3 {
    transform: translate(0, -11px) rotate(45deg);
}

#language {
    margin: 10px 15px 0 0;
    color: rgb(41, 130, 189);
}

#language select {
    border: none;
}

.dropbtn {
    background-color: #3498DB;
    color: white;
    padding: 10px;
    font-size: 12px;
    border: none;
    cursor: pointer;
    border-radius: 20px;
}

.dropbtn:hover,
.dropbtn:focus {
    background-color: #2980B9;
}

.dropdown {
    position: relative;
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #3498DB;
    min-width: 7px;
    overflow: auto;
    box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
    z-index: 1;
    margin-left: 20px;
}

.dropdown-content a {
    color: white;
    padding: 7px 5px;
    text-decoration: none;
    display: block;
    font-size: 13px;
}

.dropdown-content a:hover {
    text-decoration: underline;
}

.show {
    display: block;
}

.sidenav {
    position: absolute;
    height: 70%;
    z-index: 1;
    width: 0;
    background-color: rgb(41, 130, 189);
    overflow-x: hidden;
    transition: 0.5s;
    border-radius: 10px;
    padding: 0;
    color: white
}

.btns {
    display: flex;
    justify-content: center;
    gap: 17px;
    margin-bottom: 5px;
    margin: 20px;
}

.btn {
    border: solid 2px rgb(24, 24, 119);
    padding: 10px;
    border-radius: 10px;
    background: none;
    color: rgb(24, 24, 119);
}

.btn:hover {
    box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.3);
    border: solid 2px white;
    color: white;
}

.closebtn {
    place-items: center;
    text-decoration: none;
    font-size: 20px;
    text-align: center;
    margin: 15px;
}

.theme,
.authors {
    position: relative;
    padding: 5px;
    border: solid 1px rgb(29, 33, 139);
    border-radius: 10px;
    margin: 20px;
}

.sidenav h3 {
    left: 15px;
    margin: 10px;
    color: #c2bcbc;
    text-align: center;
    background-color: none;
    z-index: 1;
}

.authors {
    height: 50%;
}

.authors p {
    text-align: center;
    color: #13145e;
}

.theme {
    margin: 40px 20px;
    text-align: center;
}

#main {
    width: 100vw;
    background-color: #51abb5;
}

.container {
    color: rgb(41, 130, 189);
    width: 100%;
    display: flex;
    flex-direction: column;
    place-items: center;
}

.input-currency {
    width: 50%;
    height: 70px;
    /* background-color: chartreuse; */
    display: flex;
    border: solid 1px #111;
    border-radius: 10px;
    padding: 5px;
    gap: 5px;
}

.input-currency:hover {
    border: solid 2px rgb(41, 130, 189);
}

.form1 {
    width: 90%;
    margin: 5px;
    /* background-color: gold; */
}

#output1,
#output2 {
    color: red;
}

.subject,
.inputs {
    width: 100%;
    height: 50%;
    border-radius: 8px;
}

.subject {
    border: none;
    margin-bottom: 0.5ch;
}

#btn1,
#btn2 {
    width: 20%;
    border: solid 2px rgb(41, 130, 189);
    border-radius: 10px;
    background: none;
    color: rgb(41, 130, 189);
    font-weight: 600;
    font-size: 80%;
}

#keybord {
    text-align: center;
    width: 50%;
    border: solid 1px #111;
    border-bottom: none;
    border-top-left-radius: 10px;
    border-top-right-radius: 10px;
}

#keys {
    border: solid 1px #111;
    padding: 4px;
    /* background-color: aqua; */
    display: grid;
    width: 50%;
    gap: 5px;
    grid-template-columns: repeat(5, 1fr);
}

#keys button {
    width: 100%;
    background: none;
    padding: 5px;
    border: 1px solid #000000;
    border-radius: 5px;
    transition: box-shadow 0.1s ease;
}

#keys button:hover {
    border: none;
    box-shadow: 0 0 0 1.5px rgba(52, 152, 219, 0.7);
}

.btn-clear,
.btn-backspace {
    grid-column: 4/6;
}

.btn0 {
    grid-column: 1/3;
}

#history {
    text-align: center;
    border: 1px solid #111;
    width: 50%;
    margin-bottom: 40px;
    border-top: none;
    border-bottom-left-radius: 10px;
    border-bottom-right-radius: 10px;
}

.profils-divises span {
    padding-top: 14px;
    /* background-color: deeppink; */
    place-content: center;
}

.footer {
    background: rgb(41, 130, 189);
    width: 100vw;
    color: #c2bcbc;
    padding-top: 10px;
}

.divises h4 {
    text-align: center;
}

.profils-divises {
    margin: 0px 10px;
    background-color: #58bd9b;
    display: grid;
    grid-template-columns: 30% 30% 30%;
    place-content: center;
    gap: 10px;
}

.profils-divises a {
    gap: 5px;
    display: flex;
    /* background-color: cornsilk; */
    text-decoration: none;
}

.profils-divises a:hover {
    text-decoration: underline;
}

#contacts-container {
    /* background-color: coral; */
    display: flex;
    flex-direction: column;
    place-content: center;
    place-items: center;
}

.contacts ul {
    /* background-color: darkorchid;  */
    list-style-type: none;
    display: flex;
    gap: 12px;
}


.contacts a {
    color: rgb(56, 55, 55);
    transition: box-shadow 0.1s ease;
}

.contacts a:hover {
    color: #e7e3e3;
}

.footer2 {
    margin: 20px 0 20px 0;
    display: flex;
    gap: 80px;
    list-style-type: none;
    /* background-color: #e8e8d7;  */
}

.footer2 a,
.footer3 a {
    text-decoration: none;
}

.footer2 a:hover,
.footer3 a:hover {
    text-decoration: underline;
}

@media (width <=480px) {

    #menu-btn {
        margin: 18px 0 0 10px
    }

    #language {
        margin: 18px 10px 0 0;
    }

    .dropbtn {
        padding: 7px;
        font-size: 9px;
    }

    .dropdown-content a {
        font-size: 8.5px;
    }

    #logo {
        padding-right: 10px;
        width: 30%;
        gap: 1px;
        margin-left: 80px;
    }

    .profils-divises {
        grid-template-columns: repeat(2, 1fr);
    }

    .profils-divises a {
        font-size: 12px;
        margin: 0;
    }

    .footer2 {
        gap: 20px;
    }

    #keys,
    #history,
    #keybord,
    .input-currency {
        width: 91%;
    }

    #btn1,
    #btn2 {
        font-size: 60%;
    }

    .container h2,
    #keybord,
    h3 {
        font-size: 90%;
    }

    #logo img {
        margin-top: 10px;
        /* background-color: gold; */
        width: 20px;
        height: 20px;
    }

    #language select {
        /* background-color: chocolate; */
        font-size: 10px;
    }

    #language i {
        font-size: 12px;
    }

    .authors {
        height: 40%;
        background-color: brown;
    }

    .theme {
        background-color: crimson;
    }

    #container {
        margin: 8px 15px;
    }

    .bar {
        height: 3.5px;
        width: 25px;
    }
}

/*
By: PalancaTechnologies Softwares 
CEO: Júnior Futa
a.k.a: JFuta21
Email: juniorfuta94@gmail.com
Instagram: @juniorfuta
*/

```
